import { EMAIL_CREATE_DRAFT_INSTRUCTIONS } from "../tools/gmail/EmailCreateDraft";
import { RESOLVE_CONTACT_INSTRUCTIONS } from "../tools/gmail/ResolveContact";

export const ALL_TOOLS_DESCRIPTION = `
  ${CONTACT_RESOLVE_INSTRUCTIONS}\n
  ${EMAIL_CREATE_DRAFT_INSTRUCTIONS}\n
  ${RESOLVE_CONTACT_INSTRUCTIONS}
  `;
